[es_master]
es-master-1 ansible_host=192.168.3.221
es-master-2 ansible_host=192.168.3.222
es-master-3 ansible_host=192.168.3.223

[es_data]
es-data-1 ansible_host=192.168.3.231
es-data-2 ansible_host=192.168.3.232
es-data-3 ansible_host=192.168.3.233

[all:vars]
ansible_user=ali
